language: csharp
matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode9.2
env:
  global:
    - Configuration=Release
    - ShortVersion=1.0.0
mono: none
dotnet: 2.0.0
script:
 - set -e
 - cd build
 - ./build.sh