language: csharp
matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode8.3
env:
  global:
    - Configuration=Release
mono: none
dotnet: 2.2.100
branches:
  only:
  - master
  - /^release\/.*$/
  - develop
before_script:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB; rvm get stable; fi
script:
 - set -e
 - cd build
 - export PATH="$PATH:/home/travis/.dotnet/tools"
 - ./build.sh