language: csharp
matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode10.1
env:
  global:
    - Configuration=Release
mono: none
dotnet: 2.2.100
branches:
  only:
  - master
  - /^release\/.*$/
  - develop
script:
 - set -e
 - cd build
 - export PATH="$PATH:/home/travis/.dotnet/tools"
 - ./build.sh