language: csharp
matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode8.3
env:
  global:
    - Configuration=Release
mono: none
dotnet: 2.1.301
branches:
  only:
  - master
  - /^release\/.*$/
  - develop
before_script:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -sSL https://rvm.io/mpapis.asc | gpg --import -; rvm get stable; fi
script:
 - set -e
 - cd build
 - export PATH="$PATH:/home/travis/.dotnet/tools"
 - ./build.sh