language: csharp
matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode8.3
env:
  global:
    - Configuration=Release
    - ShortVersion=1.0.0
mono: none
dotnet: 2.0.0
before_script:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3; rvm get stable; fi
script:
 - set -e
 - cd build
 - ./build.sh