version: '{build}'

image:
- Ubuntu

configuration: Release

init:
- cat ~/.config/NuGet/NuGet.Config
- cat ~/.nuget/NuGet/NuGet.Config

nuget:
  project_feed: true
  disable_publish_on_pr: true
  
build_script:
- cd build
- ./build.sh

artifacts:
- path: build\artifacts\*.nupkg

deploy: off
